### ISSUE TITLE
Error en windows con MySQL

### ISSUE THREAD

**Issue by Dizdyt** [javinotfound/DownTown-RP#13]
Me está dando errores con mysql en windows ya que por el momento solo es para testear, si me podrías contactar para ver cual es el error más a profundo y ver si me puedes brindar una ayuda, te lo agradecería.

Aqui estan los logs 

https://www.mediafire.com/file/92xii1k3phduclq/server.log/file

**Comment by javier-es** [comment]
Hola,

Tal y como se puede ver en la línea 17, `[2022-01-12 11:08:26] Server shutdown as requested by resource sql (MySQL module missing.)`, el problema se encuentra con el módulo MySQL.

Desconozco si estás en Windows o en Linux, dado que en el título dices que estás en Linux, pero en el post pones que estás en Windows. Independientemente de que si aportas el SO te pueda dar instrucciones más concretas, te recomiendo que sigas los pasos de instalación, en concreto los relacionados con la instalación del módulo MySQL: 

[https://github.com/javier-es/DownTown-RP#instrucciones-para-la-instalaci%C3%B3n](https://github.com/javier-es/DownTown-RP#instrucciones-para-la-instalaci%C3%B3n)

Aquí también tienes algún detalle sobre cómo instalar el módulo:

[https://github.com/javier-es/DownTown-RP/issues/3#issuecomment-970304614](https://github.com/javier-es/DownTown-RP/issues/3#issuecomment-970304614)

Quedo, de todas formas, a la espera de que confirmes el sistema operativo que estás utilizando.

Un saludo.

**Comment by Dizdyt** [comment]
El sistema que estoy utilizando es windows me confundí al pone linux

**Comment by Dizdyt** [comment]
Espero me puedas ayudar ya que estoy aprendiendo sobre los modulos y mi problema es en windows
