### ISSUE TITLE
Error en la página de inicio de sesión

### ISSUE THREAD

**Issue by PatalJunior** [javinotfound/DownTown-RP#14]
Warning: Undefined array key "token" in C:\xampp\htdocs\login\auxiliar.php on line 306

Warning: Undefined array key "ip" in C:\xampp\htdocs\login\auxiliar.php on line 307

Creo que es algo que no hice, pero la documentación no parece tener mucha información sobre la página /login y /foro, la ayuda sería apreciada.

**Comment by javier-es** [comment]
Hola @PatalJunior ,

Necesito que me des algo más de información respecto a lo que estás tratando de hacer, y de cómo llegas a obtener dichos logs.. Esos errores vienen porque en la sesión PHP no están los atributos token e IP y, por tanto, devuelve ese error. Es decir, estás llamando a la función comprobarSesionCliente() sin que el usuario se haya identificado en el login.
